
***
Time:
12.05.2020 7:53:19
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:53:22
Exception:
System.AggregateException: One or more errors occurred. (Invalid URI: The hostname could not be parsed.) ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NodeApp.LicensorClasses.LicensorClient.ConnectAndListenAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 103
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at NodeApp.LicensorClasses.LicensorClient..ctor() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 66
---> (Inner Exception #0) System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NodeApp.LicensorClasses.LicensorClient.ConnectAndListenAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 103<---

TEXT:


***
Time:
12.05.2020 7:53:22
Exception:
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NodeApp.LicensorClasses.LicensorClient.ConnectAndListenAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 103
   at NodeApp.LicensorClasses.LicensorClient.TryConnectAsync(Boolean authRequired) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 81
TEXT:


***
Time:
12.05.2020 7:53:22
Exception:
NodeApp.LicensorException: Unable to establish connection with licensor.
   at NodeApp.LicensorClasses.LicensorClient.GetLicenseAsync(Nullable`1 nodeId) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 447
TEXT:


***
Time:
12.05.2020 7:53:23
Exception:
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NodeApp.LicensorClasses.LicensorClient.ConnectAndListenAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 103
   at NodeApp.LicensorClasses.LicensorClient.TryConnectAsync(Boolean authRequired) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 81
TEXT:


***
Time:
12.05.2020 7:53:23
Exception:
NodeApp.LicensorException: Unable to establish connection with licensor.
   at NodeApp.LicensorClasses.LicensorClient.GetLicenseAsync(Nullable`1 nodeId) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\LicensorClasses\LicensorClient.cs:line 447
TEXT:


***
Time:
12.05.2020 7:53:24
Exception:
System.AggregateException: One or more errors occurred. (Синтаксическая ошибка в имени файла, имени папки или метке тома : 'D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\https:\api\Blockchain\FindMatch') ---> System.Net.WebException: Синтаксическая ошибка в имени файла, имени папки или метке тома : 'D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\https:\api\Blockchain\FindMatch' ---> System.IO.IOException: Синтаксическая ошибка в имени файла, имени папки или метке тома : 'D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\https:\api\Blockchain\FindMatch'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Net.FileWebRequest.CreateWriteStream()
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.CreateWriteStream()
   at System.Net.FileWebRequest.<>c.<GetRequestStreamAsync>b__56_0(Object s)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__275_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.WebClient.UploadBitsAsync(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer, AsyncOperation asyncOp, Action`3 completionDelegate)
   at NodeApp.Blockchain.BlockchainSynchronizationService.CommonBlockchainPartSearchAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockchainSynchronizationService.cs:line 128
   at NodeApp.Blockchain.BlockchainSynchronizationService.CheckAndSyncBlockchainAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockchainSynchronizationService.cs:line 31
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at NodeApp.Startup.Configure(IApplicationBuilder app, IApplicationLifetime applicationLifetime) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Startup.cs:line 276
---> (Inner Exception #0) System.Net.WebException: Синтаксическая ошибка в имени файла, имени папки или метке тома : 'D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\https:\api\Blockchain\FindMatch' ---> System.IO.IOException: Синтаксическая ошибка в имени файла, имени папки или метке тома : 'D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\https:\api\Blockchain\FindMatch'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Net.FileWebRequest.CreateWriteStream()
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.CreateWriteStream()
   at System.Net.FileWebRequest.<>c.<GetRequestStreamAsync>b__56_0(Object s)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__275_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.WebClient.UploadBitsAsync(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer, AsyncOperation asyncOp, Action`3 completionDelegate)
   at NodeApp.Blockchain.BlockchainSynchronizationService.CommonBlockchainPartSearchAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockchainSynchronizationService.cs:line 128
   at NodeApp.Blockchain.BlockchainSynchronizationService.CheckAndSyncBlockchainAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockchainSynchronizationService.cs:line 31<---

TEXT:


***
Time:
12.05.2020 7:53:50
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:54:20
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:54:50
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:55:21
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:55:51
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:56:21
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:56:51
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:57:21
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:57:51
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:58:21
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:58:51
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:59:23
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 7:59:53
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:00:23
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:00:53
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:01:23
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:01:53
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:02:23
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:02:59
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:03:29
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:03:59
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:04:29
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:05:00
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:05:30
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:06:00
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:06:30
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:07:00
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:07:30
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:08:00
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:08:30
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:09:00
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:09:30
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:10:00
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:10:30
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:11:00
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:11:31
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:12:01
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:12:31
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:13:01
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:13:31
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:14:01
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:14:31
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:15:01
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:15:31
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:16:01
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:16:31
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:17:01
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:17:32
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:18:02
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:18:32
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:19:02
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:19:32
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:20:02
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:20:32
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:21:02
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:21:32
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:22:02
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:22:32
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:23:02
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:23:33
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:24:03
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:24:33
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:25:03
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:25:33
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:26:03
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:26:33
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:27:03
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:27:33
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:28:03
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:28:33
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:29:03
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:29:33
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:30:04
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:30:34
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:31:04
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:31:34
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:32:04
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:32:34
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:33:04
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:33:34
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:34:04
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:34:34
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:35:04
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:35:34
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:36:04
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:36:35
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:


***
Time:
12.05.2020 8:37:05
Exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: LLEN LSEGMENTS; SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:6379/Subscription, origin: Error, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 18751s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2000
--- End of stack trace from previous location where exception was thrown ---
   at NodeApp.CacheStorageClasses.RedisBlockSegmentRepository.GetCount(String key) in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\CacheStorageClasses\RedisBlockSegmentRepository.cs:line 49
   at NodeApp.Blockchain.BlockSegmentsCacheService.GetBlockSegmentsCount() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\BlockSegmentsCacheService.cs:line 51
   at NodeApp.Blockchain.AppBlockGenerationHelper.CheckQueueAsync() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 81
   at NodeApp.Blockchain.AppBlockGenerationHelper.<.ctor>b__8_0() in D:\OldNotebookWindows\Users\user\Documents\ymessenger\NodeApp\Blockchain\AppBlockGenerationHelper.cs:line 46
TEXT:

